# -*- coding: utf-8 -*-
"""data_preprocessing_dashboard (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WfV4eojjYOfWxc5oYKYlIPnYYsMCH8e
"""

!pip install gdown

import os
import gdown
import zipfile

def download_files_from_drive(output_dir="./data"):
    """
    Download required files from Google Drive.

    Args:
        output_dir: Directory to save downloaded files
    """
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # File IDs and destination filenames
    files_to_download = {
        # You need to replace these with actual file IDs from Google Drive
        "1BYDShV6D4elrdtMrAI1hMcupQLiZ-sQ0": "llm2vec_llama38B_embeddings_2011_2018.zip"
    }

    for file_id, filename in files_to_download.items():
        output_path = os.path.join(output_dir, filename)

        print(f"Downloading {filename}...")
        try:
            gdown.download(f"https://drive.google.com/uc?id={file_id}", output_path, quiet=False)
            print(f"Successfully downloaded {filename}")

            # Extract zip files
            if filename.endswith(".zip"):
                print(f"Extracting {filename}...")
                with zipfile.ZipFile(output_path, 'r') as zip_ref:
                    extract_path = os.path.join(output_dir, os.path.splitext(filename)[0])
                    os.makedirs(extract_path, exist_ok=True)
                    zip_ref.extractall(extract_path)
                print(f"Successfully extracted {filename} to {extract_path}")

        except Exception as e:
            print(f"Error downloading {filename}: {e}")

    print("All downloads completed")

if __name__ == "__main__":
    download_files_from_drive()

import os
import re
import json
from collections import defaultdict
from tqdm import tqdm

class BREFHierarchyProcessor:
    def __init__(self, input_dir, output_dir="./processed_data"):
        """
        Process BREF files to extract hierarchical structure.

        Args:
            input_dir (str): Directory containing BREF section files
            output_dir (str): Directory to save processed data
        """
        self.input_dir = input_dir
        self.output_dir = output_dir
        self.sections = {}  # {section_id: {'title': title, 'content': content}}
        self.section_hierarchy = defaultdict(list)  # {chapter: [section_ids]}
        self.bref_codes = set()  # Set of unique BREF codes

        # Create output directory
        os.makedirs(output_dir, exist_ok=True)

    def parse_files(self):
        """Parse all BREF files and extract section information"""
        print("Parsing BREF files...")
        files = []

        # Walk through the directory and collect all .txt files
        for root, _, filenames in os.walk(self.input_dir):
            for filename in filenames:
                if filename.endswith('.txt'):
                    files.append(os.path.join(root, filename))

        print(f"Found {len(files)} BREF files")

        for file_path in tqdm(files):
            self._process_file(file_path)

        print(f"Processed {len(self.sections)} sections across {len(self.bref_codes)} BREF documents")

    def _process_file(self, file_path):
        """
        Process a single BREF section file.

        Args:
            file_path (str): Path to the section file
        """
        # Extract BREF code from the path
        path_parts = file_path.split(os.sep)
        if len(path_parts) > 1:
            bref_code = path_parts[-2]  # Assume the parent folder is the BREF code
            self.bref_codes.add(bref_code)
        else:
            bref_code = "UNKNOWN"

        # Extract section ID and title from filename
        filename = os.path.basename(file_path)
        section_id, title = self._parse_filename(filename)

        if not section_id:
            return  # Skip files without valid section IDs

        # Create a full section ID with BREF code
        full_section_id = f"{bref_code}:::{section_id}"

        # Read file content
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except UnicodeDecodeError:
            try:
                with open(file_path, 'r', encoding='latin-1') as f:
                    content = f.read()
            except Exception as e:
                print(f"Error reading {file_path}: {e}")
                return

        # Store section info
        self.sections[full_section_id] = {
            'title': title,
            'content': content,
            'file_path': file_path,
            'bref_code': bref_code
        }

        # Add to hierarchy
        if '.' in section_id:
            chapter = section_id.split('.')[0]
        else:
            chapter = section_id

        chapter_key = f"{bref_code}:::{chapter}"
        self.section_hierarchy[chapter_key].append(full_section_id)

    def _parse_filename(self, filename):
        """
        Parse section ID and title from filename.

        Args:
            filename (str): Filename of BREF section

        Returns:
            tuple: (section_id, title)
        """
        # Remove file extension
        base_name = os.path.splitext(filename)[0]

        # Handle special cases for metadata files
        if base_name.startswith('_'):
            return None, base_name[1:]

        # Extract section ID and title
        match = re.match(r'^(\d+(?:\.\d+)*(?:\.\d+)*(?:\.\d+)*)_(.+)$', base_name)
        if match:
            section_id = match.group(1)
            title = match.group(2).replace('_', ' ')
            return section_id, title

        # Handle chapter files like "1_GENERAL INFORMATION.txt"
        match = re.match(r'^(\d+)_(.+)$', base_name)
        if match:
            section_id = match.group(1)
            title = match.group(2).replace('_', ' ')
            return section_id, title

        return None, base_name

    def build_hierarchy(self):
        """Build the hierarchical structure for the dashboard"""
        print("Building hierarchical structure...")

        # Group sections by BREF code
        bref_structures = {}

        for bref_code in self.bref_codes:
            # Find all sections for this BREF
            bref_sections = {k: v for k, v in self.sections.items() if v['bref_code'] == bref_code}

            # Start with chapters
            chapter_sections = {k: v for k, v in bref_sections.items() if '.' not in k.split(':::')[1]}

            # Sort chapters
            sorted_chapters = sorted(chapter_sections.keys(),
                                      key=lambda x: int(x.split(':::')[1]) if x.split(':::')[1].isdigit() else float('inf'))

            # Create hierarchical structure
            bref_hierarchy = []

            for chapter_id in sorted_chapters:
                chapter_obj = {
                    'id': chapter_id,
                    'name': chapter_sections[chapter_id]['title'],
                    'children': []
                }

                # Get all subsections for this chapter
                chapter_num = chapter_id.split(':::')[1]
                subsections = {k: v for k, v in bref_sections.items()
                               if k != chapter_id and k.split(':::')[1].startswith(f"{chapter_num}.")}

                # Add subsections recursively
                self._add_children(chapter_obj, subsections)

                bref_hierarchy.append(chapter_obj)

            bref_structures[bref_code] = bref_hierarchy

        # Save hierarchical structure to JSON
        output_path = os.path.join(self.output_dir, "bref_hierarchy.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(bref_structures, f, indent=2)

        print(f"Saved hierarchical structure to {output_path}")
        return bref_structures

    def _add_children(self, parent, sections):
        """
        Recursively add children to parent section.

        Args:
            parent (dict): Parent section object
            sections (dict): Dictionary of sections to process
        """
        parent_id = parent['id']
        parent_path = parent_id.split(':::')[1]

        # Find direct children (one level deeper)
        direct_children = {}
        for section_id, section in sections.items():
            section_path = section_id.split(':::')[1]

            # Check if this is a direct child
            if section_path.count('.') == parent_path.count('.') + 1 and section_path.startswith(f"{parent_path}."):
                direct_children[section_id] = section

        # Sort children
        sorted_children = sorted(direct_children.keys(),
                                 key=lambda x: [int(p) if p.isdigit() else 0 for p in x.split(':::')[1].split('.')])

        # Add each child and its children
        for child_id in sorted_children:
            child_obj = {
                'id': child_id,
                'name': direct_children[child_id]['title'],
                'children': []
            }

            # Recursively add children to this child
            self._add_children(child_obj, sections)

            # Add to parent's children
            parent['children'].append(child_obj)

    def process(self):
        """Run the full processing pipeline"""
        self.parse_files()
        hierarchy = self.build_hierarchy()
        return hierarchy

if __name__ == "__main__":
    # Adjust this path to the directory containing BREF text files
    input_dir = "./QUERIES_notab_noacronyms"  # Update this path

    processor = BREFHierarchyProcessor(input_dir)
    hierarchy = processor.process()

    print("BREF hierarchy processing complete!")

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import umap
import zipfile
from sklearn.preprocessing import StandardScaler
import json

# Paths
data_dir = "./data"
output_dir = "./dashboard_data"
os.makedirs(output_dir, exist_ok=True)

print("Loading patent data...")
# Load just the patent data from the patent-BREF file
patent_file = os.path.join(data_dir, "bref_patents_with_LLM_scores_llama3_giordano-patents_brefs_GS12_enhanced.csv")
patent_df = pd.read_csv(patent_file)
print(f"Loaded {len(patent_df)} patents")

# Print column names to see what text fields are available
print(f"Available patent columns: {patent_df.columns.tolist()}")

# Extract unique patents for processing
unique_patents = patent_df['APPLN_ID'].unique()
print(f"Found {len(unique_patents)} unique patent IDs")

# If we have too many patents, take a subset for faster processing
max_patents = 5000000  # Very large number to include all patents
if len(unique_patents) > max_patents:
    print(f"Taking a random subset of {max_patents} patents")
    np.random.seed(42)  # For reproducibility
    subset_patents = np.random.choice(unique_patents, max_patents, replace=False)
else:
    subset_patents = unique_patents

print("Loading patent embeddings from multiple files...")

# Function to extract zip file if needed
def extract_zip_if_needed(zip_path, extract_dir):
    """Extract zip file if the extract directory doesn't exist"""
    if not os.path.exists(extract_dir):
        print(f"Extracting {zip_path} to {extract_dir}...")
        os.makedirs(extract_dir, exist_ok=True)
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_dir)
        print(f"Extraction complete")
    else:
        print(f"Using already extracted files in {extract_dir}")

# Prepare both embedding files
embedding_files = []

# 1. First embedding file (>2018)
zip_path_gt2018 = os.path.join(data_dir, "llm2vec_llama38B_embeddings_gt2018.zip")
extract_dir_gt2018 = os.path.join(data_dir, "llm2vec_llama38B_embeddings_gt2018")
extract_zip_if_needed(zip_path_gt2018, extract_dir_gt2018)

# Find parquet file in the extracted directory
parquet_files_gt2018 = [f for f in os.listdir(extract_dir_gt2018) if f.endswith('.parquet')]
if parquet_files_gt2018:
    embedding_files.append(os.path.join(extract_dir_gt2018, parquet_files_gt2018[0]))
    print(f"Found embeddings file for post-2018: {parquet_files_gt2018[0]}")

# 2. Second embedding file (2011-2018)
zip_path_2011_2018 = os.path.join(data_dir, "llm2vec_llama38B_embeddings_2011_2018.zip")
extract_dir_2011_2018 = os.path.join(data_dir, "llm2vec_llama38B_embeddings_2011_2018")
extract_zip_if_needed(zip_path_2011_2018, extract_dir_2011_2018)

# Find parquet file in the second extracted directory
parquet_files_2011_2018 = [f for f in os.listdir(extract_dir_2011_2018) if f.endswith('.parquet')]
if parquet_files_2011_2018:
    embedding_files.append(os.path.join(extract_dir_2011_2018, parquet_files_2011_2018[0]))
    print(f"Found embeddings file for 2011-2018: {parquet_files_2011_2018[0]}")

# Check if we found any embedding files
if not embedding_files:
    raise FileNotFoundError("No parquet embedding files found in the extracted directories")

# Load and combine all embedding files
combined_embeddings = []
for file in embedding_files:
    print(f"Loading embeddings from {file}...")
    df = pd.read_parquet(file)
    combined_embeddings.append(df)
    print(f"Loaded {len(df)} embeddings with columns: {df.columns.tolist()}")

# Combine all embeddings into a single dataframe
embeddings_df = pd.concat(combined_embeddings, ignore_index=True)
print(f"Combined embeddings dataframe has {len(embeddings_df)} rows")

# Check for and remove any duplicates
if embeddings_df['APPLN_ID'].duplicated().any():
    duplicate_count = embeddings_df['APPLN_ID'].duplicated().sum()
    print(f"Found {duplicate_count} duplicate patent IDs, keeping first occurrence only")
    embeddings_df = embeddings_df.drop_duplicates(subset='APPLN_ID', keep='first')
    print(f"After removing duplicates, dataframe has {len(embeddings_df)} rows")

# Check the structure of the embedding column
embedding_sample = embeddings_df['embedding'].iloc[0]
print(f"Embedding sample type: {type(embedding_sample)}")
print(f"Embedding sample shape: {np.array(embedding_sample).shape if hasattr(embedding_sample, '__iter__') else 'Not iterable'}")

# Match patents with embeddings
print("Matching patents with embeddings...")
matched_patents = []
for pid in tqdm(subset_patents):
    # Try to find the patent in the embeddings dataframe
    matches = embeddings_df[embeddings_df['APPLN_ID'] == pid]
    if not matches.empty:
        # Add the patent with its embedding
        patent_data = patent_df[patent_df['APPLN_ID'] == pid].iloc[0]

        # Get available text from the patent data
        patent_info = {
            'APPLN_ID': pid,
            'APPLN_TITLE': patent_data['APPLN_TITLE'],
            'APPLN_YR': patent_data['APPLN_YR'],
            'embedding': matches.iloc[0]['embedding']
        }

        # Add 'Text' field if available (abstract/description)
        if 'Text' in patent_data:
            patent_info['Text'] = patent_data['Text']
        # Check for 'APPLN_ABSTR' field in embeddings
        elif 'APPLN_ABSTR' in matches.columns:
            patent_info['Text'] = matches.iloc[0]['APPLN_ABSTR']

        # Add additional text fields if available
        for field in ['APPLN_ABSTR', 'bref_text']:
            if field in patent_data:
                patent_info[field] = patent_data[field]

        matched_patents.append(patent_info)

print(f"Matched {len(matched_patents)} patents with embeddings")

if len(matched_patents) == 0:
    print("No matches found. Checking for format issues...")
    # Check if the format of APPLN_ID might be different between dataframes
    patent_id_sample = patent_df['APPLN_ID'].iloc[0]
    embedding_id_sample = embeddings_df['APPLN_ID'].iloc[0]
    print(f"Patent ID sample: {patent_id_sample}, type: {type(patent_id_sample)}")
    print(f"Embedding ID sample: {embedding_id_sample}, type: {type(embedding_id_sample)}")

    # Try converting to same type and check for matches
    if type(patent_id_sample) != type(embedding_id_sample):
        print("ID types don't match, trying conversion...")
        converted_matches = 0
        for pid in subset_patents[:100]:  # Check just 100 for speed
            # Try different conversions
            conversions = [str(pid), int(pid) if str(pid).isdigit() else None]
            for conv_pid in conversions:
                if conv_pid is not None and any(embeddings_df['APPLN_ID'] == conv_pid):
                    converted_matches += 1
        print(f"Found {converted_matches} matches after conversion")

    # If still no matches, try a different approach
    if converted_matches == 0:
        print("Still no matches. Using a subset of embeddings instead.")
        subset_size = min(1000, len(embeddings_df))
        matched_patents = []
        for _, row in embeddings_df.head(subset_size).iterrows():
            patent_info = {
                'APPLN_ID': row['APPLN_ID'],
                'APPLN_TITLE': row.get('APPLN_TITLE', f"Patent {row['APPLN_ID']}"),
                'APPLN_YR': row.get('APPLN_YR', 2020),
                'embedding': row['embedding']
            }

            # Add any available text fields
            for field in ['APPLN_ABSTR', 'Text']:
                if field in row:
                    patent_info[field] = row[field]

            matched_patents.append(patent_info)

        print(f"Using {len(matched_patents)} patents from embeddings dataframe")

# Extract embeddings for UMAP
print("Preparing embeddings for UMAP...")
patent_ids = [p['APPLN_ID'] for p in matched_patents]
embedding_matrix = np.array([np.array(p['embedding']) for p in matched_patents])

print(f"Embedding matrix shape: {embedding_matrix.shape}")

# Apply UMAP
print("Applying UMAP dimensionality reduction...")
scaler = StandardScaler()
normalized_embeddings = scaler.fit_transform(embedding_matrix)

# Use appropriate n_neighbors (less than number of samples)
n_neighbors = min(15, len(normalized_embeddings) - 1)
reducer = umap.UMAP(
    n_components=2,
    n_neighbors=n_neighbors,
    min_dist=0.1,
    metric='cosine',
    random_state=42
)

# Apply UMAP and track progress
embedding_2d = reducer.fit_transform(normalized_embeddings)

# Create dataframe with results
print("Creating output dataframe...")
# Create a base dataframe with the coordinates
coords_df = pd.DataFrame({
    'APPLN_ID': patent_ids,
    'x': embedding_2d[:, 0],
    'y': embedding_2d[:, 1],
    'title': [p['APPLN_TITLE'] for p in matched_patents],
    'year': [p['APPLN_YR'] for p in matched_patents]
})

# Add text fields if available
if any('Text' in p for p in matched_patents):
    coords_df['text'] = [p.get('Text', '') for p in matched_patents]

# Add abstract if available
if any('APPLN_ABSTR' in p for p in matched_patents):
    coords_df['abstract'] = [p.get('APPLN_ABSTR', '') for p in matched_patents]

# Add BREF text if available
if any('bref_text' in p for p in matched_patents):
    coords_df['bref_text'] = [p.get('bref_text', '') for p in matched_patents]

# Normalize coordinates to [0,1] range
coords_df['x'] = (coords_df['x'] - coords_df['x'].min()) / (coords_df['x'].max() - coords_df['x'].min())
coords_df['y'] = (coords_df['y'] - coords_df['y'].min()) / (coords_df['y'].max() - coords_df['y'].min())

# Save the results
print("Saving results...")
coords_df.to_csv(os.path.join(output_dir, "patent_coordinates.csv"), index=False)
coords_dict = coords_df.to_dict(orient='records')

# Save to JSON, handling potentially large text fields
try:
    with open(os.path.join(output_dir, "patent_coordinates.json"), 'w') as f:
        json.dump(coords_dict, f, indent=2)
    print("Saved full JSON with all text fields")
except Exception as e:
    print(f"Error saving full JSON: {e}")
    print("Trying to save without text fields...")

    # Create a simplified version without large text fields
    simplified_coords = coords_df.drop(columns=[col for col in coords_df.columns if col in ['text', 'abstract', 'bref_text']])
    simplified_dict = simplified_coords.to_dict(orient='records')

    with open(os.path.join(output_dir, "patent_coordinates_simplified.json"), 'w') as f:
        json.dump(simplified_dict, f, indent=2)
    print("Saved simplified JSON without text fields")

print("UMAP projection complete!")

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
import os
import seaborn as sns

def visualize_umap_projection(file_path="./dashboard_data/patent_coordinates.csv", output_dir="./dashboard_data"):
    """
    Create visualizations of the UMAP patent space projections.

    Args:
        file_path: Path to the CSV with patent coordinates
        output_dir: Directory to save visualization images
    """
    # Load the data
    print(f"Loading patent coordinates from {file_path}")
    coords_df = pd.read_csv(file_path)
    print(f"Loaded {len(coords_df)} patent coordinates")

    # Basic scatter plot
    plt.figure(figsize=(12, 10))
    plt.scatter(coords_df['x'], coords_df['y'], alpha=0.6, s=5, c='blue')
    plt.title('UMAP Projection of Patent Embeddings', fontsize=16)
    plt.xlabel('UMAP Dimension 1', fontsize=12)
    plt.ylabel('UMAP Dimension 2', fontsize=12)
    plt.grid(alpha=0.3)

    # Add some random labels to the plot (every n-th point)
    n = max(1, len(coords_df) // 20)  # Show ~20 labels
    for i, row in coords_df.iloc[::n].iterrows():
        plt.annotate(
            row['title'][:30] + '...' if len(row['title']) > 30 else row['title'],
            (row['x'], row['y']),
            fontsize=8,
            alpha=0.8,
            xytext=(5, 5),
            textcoords='offset points',
            bbox=dict(boxstyle="round,pad=0.3", fc="white", alpha=0.8)
        )

    plt.tight_layout()
    base_plot_path = os.path.join(output_dir, "umap_projection.png")
    plt.savefig(base_plot_path, dpi=300)
    print(f"Saved basic plot to {base_plot_path}")
    plt.close()

    # Colored by year if available
    if 'year' in coords_df.columns:
        plt.figure(figsize=(12, 10))

        # Create a custom colormap
        cmap = plt.cm.viridis

        # Scatter plot colored by year
        scatter = plt.scatter(
            coords_df['x'],
            coords_df['y'],
            c=coords_df['year'],
            cmap=cmap,
            alpha=0.7,
            s=10,
            edgecolors='none'
        )

        # Add colorbar
        cbar = plt.colorbar(scatter)
        cbar.set_label('Patent Year', fontsize=12)

        plt.title('UMAP Projection of Patent Embeddings by Year', fontsize=16)
        plt.xlabel('UMAP Dimension 1', fontsize=12)
        plt.ylabel('UMAP Dimension 2', fontsize=12)
        plt.grid(alpha=0.3)
        plt.tight_layout()

        year_plot_path = os.path.join(output_dir, "umap_projection_by_year.png")
        plt.savefig(year_plot_path, dpi=300)
        print(f"Saved year-colored plot to {year_plot_path}")
        plt.close()

    # Density plot to show clustering
    plt.figure(figsize=(12, 10))
    sns.kdeplot(
        x=coords_df['x'],
        y=coords_df['y'],
        cmap="viridis",
        fill=True,
        thresh=0.05
    )
    plt.title('Density of Patents in the Embedding Space', fontsize=16)
    plt.xlabel('UMAP Dimension 1', fontsize=12)
    plt.ylabel('UMAP Dimension 2', fontsize=12)
    plt.tight_layout()

    density_plot_path = os.path.join(output_dir, "umap_density.png")
    plt.savefig(density_plot_path, dpi=300)
    print(f"Saved density plot to {density_plot_path}")
    plt.close()

    # Create a hexbin plot to show density in another way
    plt.figure(figsize=(12, 10))
    plt.hexbin(
        coords_df['x'],
        coords_df['y'],
        gridsize=50,
        cmap='inferno',
        mincnt=1
    )
    plt.colorbar(label='Patent Count')
    plt.title('Hexbin Density of Patents in the Embedding Space', fontsize=16)
    plt.xlabel('UMAP Dimension 1', fontsize=12)
    plt.ylabel('UMAP Dimension 2', fontsize=12)
    plt.tight_layout()

    hexbin_plot_path = os.path.join(output_dir, "umap_hexbin.png")
    plt.savefig(hexbin_plot_path, dpi=300)
    print(f"Saved hexbin plot to {hexbin_plot_path}")
    plt.close()

    print("Visualization complete!")

if __name__ == "__main__":
    visualize_umap_projection()

import os
import pandas as pd
import numpy as np
import json
import re
from tqdm import tqdm

def create_integrated_dataset(output_dir="./dashboard_data"):
    """
    Create integrated dataset combining patents, BREF sections, pollutants, and UMAP coordinates.
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Load datasets
    print("Loading datasets...")
    patent_bref_df = pd.read_csv("./data/bref_patents_with_LLM_scores_llama3_giordano-patents_brefs_GS12_enhanced.csv")
    bref_pollutant_df = pd.read_csv("new_bref_pollutant.csv")
    pollutant_sdg_df = pd.read_csv("pollutant_sdg.csv")
    coords_df = pd.read_csv("./dashboard_data/patent_coordinates.csv")

    # Debug: Print sample APPLN_ID values
    print("\nSample APPLN_ID values from patent_bref_df:")
    print(patent_bref_df['APPLN_ID'].head(5).tolist())

    print("\nSample APPLN_ID values from coords_df:")
    print(coords_df['APPLN_ID'].head(5).tolist())

    # Detailed debugging of the ID formats
    print("\n--- DETAILED ID FORMAT ANALYSIS ---")
    # Check exact length and format of IDs in both dataframes
    print(f"patent_bref_df first ID: '{patent_bref_df['APPLN_ID'].iloc[0]}', length: {len(patent_bref_df['APPLN_ID'].iloc[0])}")
    print(f"coords_df first ID: '{coords_df['APPLN_ID'].iloc[0]}', length: {len(coords_df['APPLN_ID'].iloc[0])}")

    # Check for invisible characters or whitespace
    print(f"patent_bref_df first ID bytes: {repr(patent_bref_df['APPLN_ID'].iloc[0])}")
    print(f"coords_df first ID bytes: {repr(coords_df['APPLN_ID'].iloc[0])}")

    # Print a direct comparison of the same ID in both datasets if possible
    common_id = patent_bref_df['APPLN_ID'].iloc[0]
    matching_row = coords_df[coords_df['APPLN_ID'] == common_id]
    if not matching_row.empty:
        print(f"Direct comparison possible for ID: {common_id}")
        print(f"Are they identical? {common_id == matching_row['APPLN_ID'].iloc[0]}")
    else:
        print(f"No direct match found for {common_id} in coords_df")

    # Don't clean the IDs if they match format in coordinates file
    if patent_bref_df['APPLN_ID'].iloc[0] == coords_df['APPLN_ID'].iloc[0]:
        print("ID formats match - not cleaning")
        patent_bref_df['cleaned_APPLN_ID'] = patent_bref_df['APPLN_ID']
    else:
        # Check if either has extra whitespace
        patent_bref_df['cleaned_APPLN_ID'] = patent_bref_df['APPLN_ID'].str.strip()
        print("Cleaned whitespace from IDs")

    with open("./processed_data/bref_hierarchy.json", 'r') as f:
        bref_hierarchy = json.load(f)

    # 1. Join patent-BREF data with BREF-pollutant data
    print("\nJoining patent-BREF with BREF-pollutant data...")
    # Use bref_code to match with code
    merged_df = pd.merge(
        patent_bref_df,
        bref_pollutant_df,
        left_on='bref_code',  # IMPORTANT: Use bref_code, not section_path
        right_on='code',
        how='inner'
    )

    print(f"Merged result: {len(merged_df)} rows")

    # 2. Filter and calculate relevance
    # Convert label to boolean (0/1 to False/True)
    merged_df['is_relevant'] = merged_df['label'].astype(bool)

    # Filter to only relevant connections (where pollutant is relevant to BREF)
    relevant_df = merged_df[merged_df['is_relevant']]
    print(f"Relevant connections: {len(relevant_df)} rows")

    # If no relevant connections, take top matches regardless of relevance
    if len(relevant_df) == 0:
        print("No relevant connections found. Using all connections and sorting by LLM score...")
        relevant_df = merged_df.sort_values('LLM_yes_probs', ascending=False).head(1000)

    # 3. Calculate patent-pollutant relevance
    print("\nCalculating patent-pollutant relevance scores...")
    patent_pollutant_scores = relevant_df.groupby(['cleaned_APPLN_ID', 'pollutant']).agg({
        'LLM_yes_probs': 'mean',     # Use LLM score as relevance
        'APPLN_TITLE': 'first',      # Keep the patent title
        'APPLN_YR': 'first',         # Keep the patent year
        'APPLN_ID': 'first'          # Keep the original ID
    }).reset_index()

    # Rename for clarity
    patent_pollutant_scores = patent_pollutant_scores.rename(columns={
        'LLM_yes_probs': 'relevance_score'
    })

    print(f"Generated {len(patent_pollutant_scores)} patent-pollutant pairs")

    # Print the unique pollutants before coordinates
    print("\nTop 10 pollutants before joining with coordinates:")
    pollutant_counts = patent_pollutant_scores['pollutant'].value_counts().head(10)
    for pollutant, count in pollutant_counts.items():
        print(f"  {pollutant}: {count} patents")

    # 4. Try direct matching of IDs
    print("\nAttempting to match IDs between datasets...")
    # Convert IDs in both datasets to simple strings without any suffix
    patent_pollutant_scores['simple_id'] = patent_pollutant_scores['cleaned_APPLN_ID'].str.replace('_abstract', '').str.strip()
    coords_df['simple_id'] = coords_df['APPLN_ID'].str.replace('_abstract', '').str.strip()

    # Check for matches with simplified IDs
    simple_matching_ids = set(patent_pollutant_scores['simple_id']).intersection(set(coords_df['simple_id']))
    print(f"Number of patent IDs that match using simplified IDs: {len(simple_matching_ids)}")

    # Try direct ID matching first
    direct_integrated_df = pd.merge(
        patent_pollutant_scores,
        coords_df[['APPLN_ID', 'x', 'y']],
        left_on='cleaned_APPLN_ID',
        right_on='APPLN_ID',
        how='inner'
    )

    print(f"Direct ID matching results: {len(direct_integrated_df)} matches")

    # If direct matching doesn't work well, try with simplified IDs
    if len(direct_integrated_df) < 100:
        print("Direct matching insufficient, trying simplified ID matching...")
        simplified_integrated_df = pd.merge(
            patent_pollutant_scores,
            coords_df[['simple_id', 'x', 'y']],
            on='simple_id',
            how='inner'
        )
        print(f"Simplified ID matching results: {len(simplified_integrated_df)} matches")

        if len(simplified_integrated_df) >= 100:
            integrated_df = simplified_integrated_df
        else:
            # Fall back to generating coordinates if no match method works well
            print("Both matching methods insufficient, generating coordinates for visualization")
            integrated_df = patent_pollutant_scores

            # Limit to top patents by relevance for visualization
            top_patents = integrated_df.sort_values('relevance_score', ascending=False).head(1000)

            # Generate spiral layout
            n_patents = len(top_patents)
            theta = np.linspace(0, 2*np.pi, n_patents)
            r = np.sqrt(np.random.random(n_patents)) * 0.8

            top_patents['x'] = 0.5 + r * np.cos(theta)
            top_patents['y'] = 0.5 + r * np.sin(theta)

            integrated_df = top_patents
            print(f"Generated spiral layout for {len(integrated_df)} patents")
    else:
        integrated_df = direct_integrated_df

    print(f"Final integrated dataset: {len(integrated_df)} patent-pollutant pairs")

    # 5. Create SDG impact data
    # Get unique pollutants that have patent matches
    unique_pollutants = integrated_df['pollutant'].unique()
    print(f"\nWorking with {len(unique_pollutants)} unique pollutants")

    # Print the list of pollutants to check for problematic characters
    print("First 10 pollutants:")
    for i, pollutant in enumerate(unique_pollutants[:10]):
        print(f"  {i+1}. '{pollutant}'")

    # Convert labels to numeric scores
    label_to_score = {
        'not relevant': 10,
        'weakly relevant': 30,
        'relevant': 60,
        'very relevant': 90
    }

    # Map string labels to numeric scores with fallback to 30
    pollutant_sdg_df['impact_score'] = pollutant_sdg_df['label'].apply(
        lambda x: label_to_score.get(str(x).lower().strip(), 30)
    )

    # Get unique SDGs (excluding 'not relevant')
    unique_sdgs = [
        sdg for sdg in pollutant_sdg_df['sdg_title'].unique()
        if str(sdg).lower().strip() not in ['not relevant', 'nan']
    ]

    # Create SDG data list with formatted names
    sdg_data = [f"SDG {i+1}: {sdg}" for i, sdg in enumerate(unique_sdgs)]

    # Create impact data structure
    sdg_impact_data = {}

    for i, sdg in enumerate(unique_sdgs):
        sdg_key = f"SDG {i+1}"
        sdg_impacts = []

        for pollutant in unique_pollutants:
            # Find the impact for this SDG and pollutant
            matches = pollutant_sdg_df[
                (pollutant_sdg_df['sdg_title'] == sdg) &
                (pollutant_sdg_df['pollutant'] == pollutant)
            ]

            if not matches.empty:
                impact = int(matches['impact_score'].iloc[0])
            else:
                # Default impact if no match
                impact = 30

            sdg_impacts.append({
                'pollutant': pollutant,
                'impact': impact
            })

        sdg_impact_data[sdg_key] = sdg_impacts

    # 6. Prepare final dashboard data structure
    print("\nPreparing dashboard data...")
    patent_data = {}

    # Function to clean pollutant names for filenames
    def clean_for_filename(pollutant):
        # Replace any non-alphanumeric chars with underscores, except keep basic punctuation
        cleaned = re.sub(r'[^a-zA-Z0-9_\-.]', '_', pollutant)
        # Replace multiple underscores with one
        cleaned = re.sub(r'_+', '_', cleaned)
        # Remove trailing underscores
        cleaned = cleaned.strip('_')
        return cleaned

    for pollutant in unique_pollutants:
        pollutant_patents = integrated_df[integrated_df['pollutant'] == pollutant]

        # Sort by relevance score
        pollutant_patents = pollutant_patents.sort_values('relevance_score', ascending=False)

        # Limit to top 50 patents per pollutant for performance
        if len(pollutant_patents) > 50:
            pollutant_patents = pollutant_patents.head(50)

        # Convert to the format expected by the dashboard
        patents_list = []
        for _, patent in pollutant_patents.iterrows():
            # Store ID as string, don't convert to int
            patents_list.append({
                'id': str(patent['cleaned_APPLN_ID']),
                'title': str(patent['APPLN_TITLE'])[:100],  # Limit title length
                'score': float(patent['relevance_score']),
                'x': float(patent['x']),
                'y': float(patent['y']),
                'abstract': f"Patent ID {patent['cleaned_APPLN_ID']} from year {patent['APPLN_YR']} related to {pollutant} abatement technology."
            })

        patent_data[pollutant] = patents_list

    # Create the final data structure
    dashboard_data = {
        'sdgs': sdg_data,
        'pollutants': list(unique_pollutants),
        'sdgImpact': sdg_impact_data,
        'patents': patent_data,
        'brefHierarchy': bref_hierarchy
    }

    # 7. Save to JSON files
    print("Saving dashboard data...")

    # Main dashboard data
    output_path = os.path.join(output_dir, "dashboard_data.json")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(dashboard_data, f, indent=2)

    # Save individual components (except patents which might be large)
    for key, data in dashboard_data.items():
        if key != 'patents':
            component_path = os.path.join(output_dir, f"{key}.json")
            with open(component_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2)

    # Save patents by pollutant
    patents_dir = os.path.join(output_dir, "patents")
    os.makedirs(patents_dir, exist_ok=True)

    for pollutant, patents in dashboard_data['patents'].items():
        # Clean pollutant name for file system
        safe_name = clean_for_filename(pollutant)
        pollutant_path = os.path.join(patents_dir, f"{safe_name}.json")

        # Extra check for problematic filenames
        if '/' in pollutant:
            print(f"Warning: Original pollutant name '{pollutant}' contains slash, saving as '{safe_name}'")

        with open(pollutant_path, 'w', encoding='utf-8') as f:
            json.dump(patents, f, indent=2)

    print("Data integration complete! Dashboard data is ready for use.")
    return dashboard_data

if __name__ == "__main__":
    create_integrated_dataset()

import os
import pandas as pd
import numpy as np
import json
import re
from tqdm import tqdm

# Configurable threshold - set to 0.5 as requested
RELEVANCE_THRESHOLD = 0.5

def create_integrated_dataset(output_dir="./dashboard_data", relevance_threshold=RELEVANCE_THRESHOLD):
    """
    Create integrated dataset combining patents, BREF sections, pollutants, and UMAP coordinates.
    FIXED: Now correctly calculates patent-pollutant scores as max score among matching BREF sections.
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Log the threshold being used
    print(f"Using relevance threshold: {relevance_threshold}")

    # Load datasets
    print("Loading datasets...")
    patent_bref_df = pd.read_csv("./data/bref_patents_with_LLM_scores_llama3_giordano-patents_brefs_GS12_enhanced.csv")

    # UPDATED: Use the new BREF-pollutant file
    bref_pollutant_df = pd.read_csv("new_bref_pollutant.csv")

    pollutant_sdg_df = pd.read_csv("pollutant_sdg.csv")
    coords_df = pd.read_csv("./dashboard_data/patent_coordinates.csv")

    # Print info about the datasets
    print(f"Patent-BREF data: {len(patent_bref_df)} rows, {patent_bref_df['APPLN_ID'].nunique()} unique patents")
    print(f"BREF-Pollutant data: {len(bref_pollutant_df)} rows, {bref_pollutant_df['pollutant'].nunique()} unique pollutants")
    print(f"Patent coordinate data: {len(coords_df)} rows, {coords_df['APPLN_ID'].nunique()} unique patents")

    # Distribution of LLM_yes_probs in patent-BREF data
    print("\nDistribution of LLM_yes_probs in patent-BREF data:")
    print(patent_bref_df['LLM_yes_probs'].describe([0.5, 0.6, 0.68, 0.7, 0.8, 0.9]))

    # Fix for the label column in bref_pollutant_df
    print("\nValues in the 'label' column of BREF-Pollutant data:")
    print(bref_pollutant_df['label'].value_counts())

    with open("./processed_data/bref_hierarchy.json", 'r') as f:
        bref_hierarchy = json.load(f)

    # Filter the BREF-pollutant data to only include relevant connections
    # First, make sure 'label' is a 0/1 column
    if bref_pollutant_df['label'].dtype != 'bool':
        print("\nConverting 'label' to numeric if needed...")
        try:
            # Try to convert label to numeric if it's not already
            bref_pollutant_df['label'] = pd.to_numeric(bref_pollutant_df['label'])
        except:
            # If that fails, it might be a string like 'yes'/'no'
            if bref_pollutant_df['label'].dtype == 'object':
                print("Label appears to be a string. Trying to map to 0/1...")
                label_map = {
                    'yes': 1, 'no': 0,
                    'true': 1, 'false': 0,
                    '1': 1, '0': 0
                }
                bref_pollutant_df['label_numeric'] = bref_pollutant_df['label'].str.lower().map(label_map)
                if not bref_pollutant_df['label_numeric'].isna().all():
                    print("String mapping successful!")
                    bref_pollutant_df['label'] = bref_pollutant_df['label_numeric']

    print("\nLabel distribution after processing:")
    print(bref_pollutant_df['label'].value_counts())

    # Filter to only include rows where label=1
    relevant_bref_pollutant = bref_pollutant_df[bref_pollutant_df['label'] == 1]
    print(f"Filtered BREF-pollutant data: {len(relevant_bref_pollutant)} rows (from {len(bref_pollutant_df)})")
    print(f"Unique pollutants with relevant connections: {relevant_bref_pollutant['pollutant'].nunique()}")

    # CRITICAL FIX: Create pollutant-to-bref mapping BEFORE processing patents
    print("\nCreating pollutant-to-BREF mapping...")
    pollutant_to_brefs = {}
    for _, row in relevant_bref_pollutant.iterrows():
        pollutant = row['pollutant']
        bref_code = row['code']

        if pollutant not in pollutant_to_brefs:
            pollutant_to_brefs[pollutant] = set()
        pollutant_to_brefs[pollutant].add(bref_code)

    print(f"Created mapping for {len(pollutant_to_brefs)} pollutants")
    for pollutant, brefs in list(pollutant_to_brefs.items())[:5]:  # Show first 5
        print(f"  {pollutant}: {len(brefs)} BREF sections")

    # 1. Join patent-BREF data with BREF-pollutant data
    print("\nJoining patent-BREF with BREF-pollutant data...")

    # Check for overlap between bref_code and code
    bref_codes_in_patent = set(patent_bref_df['bref_code'].unique())
    codes_in_pollutant = set(bref_pollutant_df['code'].unique())
    overlap = bref_codes_in_patent.intersection(codes_in_pollutant)

    print(f"BREF codes in patent data: {len(bref_codes_in_patent)}")
    print(f"Codes in pollutant data: {len(codes_in_pollutant)}")
    print(f"Overlap between codes: {len(overlap)} codes")

    # Use bref_code to match with code, but only for relevant connections
    merged_df = pd.merge(
        patent_bref_df,
        relevant_bref_pollutant,
        left_on='bref_code',
        right_on='code',
        how='inner'
    )

    print(f"Merged result: {len(merged_df)} rows")

    # 2. Apply the threshold to LLM_yes_probs BEFORE averaging
    print(f"\nApplying threshold {relevance_threshold} to LLM_yes_probs...")
    before_filter = len(merged_df)
    merged_df = merged_df[merged_df['LLM_yes_probs'] >= relevance_threshold]
    after_filter = len(merged_df)

    print(f"- Before filtering: {before_filter} patent-BREF-pollutant connections")
    print(f"- After filtering: {after_filter} patent-BREF-pollutant connections")
    print(f"- Removed {before_filter - after_filter} connections ({((before_filter - after_filter) / before_filter) * 100:.1f}%)")

    # 3. FIXED: Calculate patent-pollutant relevance using the correct approach
    print("\nCalculating patent-pollutant relevance scores (FIXED METHOD)...")

    patent_pollutant_scores = []

    # Process each unique patent
    unique_patents = merged_df['APPLN_ID'].unique()
    print(f"Processing {len(unique_patents)} unique patents...")

    for patent_id in tqdm(unique_patents):
        # Get all BREF connections for this patent
        patent_connections = merged_df[merged_df['APPLN_ID'] == patent_id]

        # Get patent metadata (same for all rows of this patent)
        patent_title = patent_connections['APPLN_TITLE'].iloc[0]
        patent_year = patent_connections['APPLN_YR'].iloc[0]

        # Group by pollutant for this patent
        for pollutant in patent_connections['pollutant'].unique():
            # Get all BREF connections for this patent-pollutant pair
            pollutant_connections = patent_connections[patent_connections['pollutant'] == pollutant]

            # FIXED: Take the MAXIMUM score among all BREF sections that match this pollutant
            # This is the key fix - we're now taking the max score across BREF sections
            max_score = pollutant_connections['LLM_yes_probs'].max()

            patent_pollutant_scores.append({
                'APPLN_ID': patent_id,
                'pollutant': pollutant,
                'relevance_score': max_score,
                'APPLN_TITLE': patent_title,
                'APPLN_YR': patent_year,
                'num_bref_matches': len(pollutant_connections)
            })

    # Convert to DataFrame
    patent_pollutant_scores = pd.DataFrame(patent_pollutant_scores)

    # Print distribution of relevance scores after filtering
    print("\nDistribution of relevance scores (after FIXED calculation):")
    print(patent_pollutant_scores['relevance_score'].describe([0.7, 0.75, 0.8, 0.85, 0.9, 0.95]))

    print(f"Generated {len(patent_pollutant_scores)} patent-pollutant pairs")
    print(f"Unique patents: {patent_pollutant_scores['APPLN_ID'].nunique()}")
    print(f"Unique pollutants: {patent_pollutant_scores['pollutant'].nunique()}")

    # Print the distribution of patents per pollutant before UMAP matching
    pollutant_counts_before = patent_pollutant_scores.groupby('pollutant')['APPLN_ID'].nunique()

    mean_before = pollutant_counts_before.mean() if not pollutant_counts_before.empty else 0
    median_before = pollutant_counts_before.median() if not pollutant_counts_before.empty else 0

    print("\nDistribution of patent counts per pollutant (before UMAP matching):")
    print(f"Min: {pollutant_counts_before.min() if not pollutant_counts_before.empty else 0}")
    print(f"Max: {pollutant_counts_before.max() if not pollutant_counts_before.empty else 0}")
    print(f"Mean: {mean_before:.1f}")
    print(f"Median: {median_before:.1f}")

    # Print top and bottom 5 pollutants by patent count
    if not pollutant_counts_before.empty:
        print("\nTop 5 pollutants by patent count:")
        for pollutant, count in pollutant_counts_before.sort_values(ascending=False).head(5).items():
            print(f"  {pollutant}: {count} patents")

        print("\nBottom 5 pollutants by patent count:")
        for pollutant, count in pollutant_counts_before.sort_values().head(5).items():
            print(f"  {pollutant}: {count} patents")

    # 4. Integrate with UMAP coordinates - but ONLY keep patents with coordinates
    print("\nIntegrating with coordinate data...")
    integrated_df = pd.merge(
        patent_pollutant_scores,
        coords_df[['APPLN_ID', 'x', 'y']],
        on='APPLN_ID',
        how='inner'  # Only keep patents with UMAP coordinates
    )

    # Calculate how many patents we lost
    patents_before = patent_pollutant_scores['APPLN_ID'].nunique()
    patents_after = integrated_df['APPLN_ID'].nunique()
    lost_patents = patents_before - patents_after
    lost_percentage = (lost_patents / patents_before) * 100 if patents_before > 0 else 0

    print(f"Patents before UMAP matching: {patents_before}")
    print(f"Patents after UMAP matching: {patents_after}")
    print(f"Lost patents: {lost_patents} ({lost_percentage:.1f}%)")

    # Print the distribution of patents per pollutant after UMAP matching
    pollutant_counts_after = integrated_df.groupby('pollutant')['APPLN_ID'].nunique()

    mean_after = pollutant_counts_after.mean() if not pollutant_counts_after.empty else 0
    median_after = pollutant_counts_after.median() if not pollutant_counts_after.empty else 0

    print("\nDistribution of patent counts per pollutant (after UMAP matching):")
    print(f"Min: {pollutant_counts_after.min() if not pollutant_counts_after.empty else 0}")
    print(f"Max: {pollutant_counts_after.max() if not pollutant_counts_after.empty else 0}")
    print(f"Mean: {mean_after:.1f}")
    print(f"Median: {median_after:.1f}")

    # If we have no patents with coordinates, stop here
    if len(integrated_df) == 0:
        print("\nERROR: No patents with UMAP coordinates matched. Cannot proceed.")
        return None, None

    # Continue with the rest of the function (SDG processing, etc.)
    # ... [rest of the function remains the same]

    # 5. Create SDG impact data
    # Get unique pollutants that have patent matches
    unique_pollutants = integrated_df['pollutant'].unique()
    print(f"\nWorking with {len(unique_pollutants)} unique pollutants that have UMAP coordinates")

    # Convert labels to numeric scores
    label_to_score = {
        'not relevant': 10,
        'weakly relevant': 30,
        'relevant': 60,
        'very relevant': 90
    }

    # Map string labels to numeric scores with fallback to 30
    pollutant_sdg_df['impact_score'] = pollutant_sdg_df['label'].apply(
        lambda x: label_to_score.get(str(x).lower().strip(), 30)
    )

    # Get unique SDGs (excluding 'not relevant')
    unique_sdgs = [
        sdg for sdg in pollutant_sdg_df['sdg_title'].unique()
        if str(sdg).lower().strip() not in ['not relevant', 'nan']
    ]

    # Create SDG data list with formatted names
    sdg_data = [f"SDG {i+1}: {sdg}" for i, sdg in enumerate(unique_sdgs)]

    # Create impact data structure
    sdg_impact_data = {}

    for i, sdg in enumerate(unique_sdgs):
        sdg_key = f"SDG {i+1}"
        sdg_impacts = []

        for pollutant in unique_pollutants:
            # Find the impact for this SDG and pollutant
            matches = pollutant_sdg_df[
                (pollutant_sdg_df['sdg_title'] == sdg) &
                (pollutant_sdg_df['pollutant'] == pollutant)
            ]

            if not matches.empty:
                impact = int(matches['impact_score'].iloc[0])
            else:
                # Default impact if no match
                impact = 30

            sdg_impacts.append({
                'pollutant': pollutant,
                'impact': impact
            })

        sdg_impact_data[sdg_key] = sdg_impacts

    # 6. Prepare final dashboard data structure - only using patents with UMAP coords
    print("\nPreparing dashboard data...")
    patent_data = {}

    # Track filenames to ensure consistent cleaning
    pollutant_to_filename = {}

    # Function to clean pollutant names for filenames
    def clean_for_filename(pollutant):
        # Replace any non-alphanumeric chars with underscores
        cleaned = re.sub(r'[^a-zA-Z0-9_\-.]', '_', pollutant)
        # Replace multiple underscores with one
        cleaned = re.sub(r'_+', '_', cleaned)
        # Remove trailing underscores
        cleaned = cleaned.strip('_')
        return cleaned

    # For each pollutant, process ALL patents (filtered by relevance)
    for pollutant in unique_pollutants:
        pollutant_patents = integrated_df[integrated_df['pollutant'] == pollutant]

        # Sort by relevance score for easier browsing
        pollutant_patents = pollutant_patents.sort_values('relevance_score', ascending=False)

        # Convert to the format expected by the dashboard
        patents_list = []
        for _, patent in pollutant_patents.iterrows():
            patents_list.append({
                'id': str(patent['APPLN_ID']),
                'title': str(patent['APPLN_TITLE'])[:100],  # Limit title length
                'score': float(patent['relevance_score']),
                'x': float(patent['x']),
                'y': float(patent['y']),
                'abstract': f"Patent ID {patent['APPLN_ID']} from year {patent['APPLN_YR']} related to {pollutant} abatement technology."
            })

        print(f"Pollutant {pollutant}: {len(patents_list)} patents")
        patent_data[pollutant] = patents_list

        # Create consistent filename for this pollutant
        filename = clean_for_filename(pollutant)
        pollutant_to_filename[pollutant] = filename

    # Create the final data structure
    dashboard_data = {
        'sdgs': sdg_data,
        'pollutants': list(unique_pollutants),
        'sdgImpact': sdg_impact_data,
        'patents': patent_data,
        'brefHierarchy': bref_hierarchy
    }

    # Save metadata about the dataset
    metadata = {
        "relevance_threshold": relevance_threshold,
        "creation_date": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),
        "total_patents": integrated_df['APPLN_ID'].nunique(),
        "total_pollutants": len(unique_pollutants),
        "total_patent_pollutant_pairs": len(integrated_df),
        "scoring_method": "max_score_among_matching_bref_sections"
    }

    with open(os.path.join(output_dir, "metadata.json"), 'w') as f:
        json.dump(metadata, f, indent=2)

    # 7. Save to JSON files
    print("Saving dashboard data...")

    # Main dashboard data
    output_path = os.path.join(output_dir, "dashboard_data.json")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(dashboard_data, f, indent=2)

    # Save individual components (except patents which might be large)
    for key, data in dashboard_data.items():
        if key != 'patents':
            component_path = os.path.join(output_dir, f"{key}.json")
            with open(component_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2)

    # Save patents by pollutant
    patents_dir = os.path.join(output_dir, "patents")
    os.makedirs(patents_dir, exist_ok=True)

    # Save a mapping file for pollutant filenames
    with open(os.path.join(output_dir, "pollutant_filenames.json"), 'w') as f:
        json.dump(pollutant_to_filename, f, indent=2)

    for pollutant, patents in dashboard_data['patents'].items():
        # Use our consistent filename cleaning function
        filename = pollutant_to_filename[pollutant]
        pollutant_path = os.path.join(patents_dir, f"{filename}.json")

        with open(pollutant_path, 'w', encoding='utf-8') as f:
            json.dump(patents, f, indent=2)

    print("Data integration complete! Dashboard data is ready for use.")
    return dashboard_data, pollutant_to_filename

if __name__ == "__main__":
    dashboard_data, pollutant_to_filename = create_integrated_dataset()

import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.cm import ScalarMappable
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D

def visualize_pollutant_umap(data_dir="./dashboard_data", output_dir=None):
    """
    Create UMAP visualizations of patents colored by relevance for selected pollutants.

    Args:
        data_dir: Directory containing the dashboard data
        output_dir: Directory to save visualizations (defaults to data_dir/visualizations)
    """
    if output_dir is None:
        output_dir = os.path.join(data_dir, "visualizations")

    os.makedirs(output_dir, exist_ok=True)

    # Load pollutant filename mapping
    with open(os.path.join(data_dir, "pollutant_filenames.json"), 'r') as f:
        pollutant_to_filename = json.load(f)

    # Reverse mapping for lookup
    filename_to_pollutant = {v: k for k, v in pollutant_to_filename.items()}

    # Load the list of pollutants
    with open(os.path.join(data_dir, "pollutants.json"), 'r') as f:
        pollutants = json.load(f)

    # Find patent counts for each pollutant to identify common and uncommon pollutants
    patent_counts = {}
    for pollutant in pollutants:
        try:
            filename = pollutant_to_filename[pollutant]
            with open(os.path.join(data_dir, "patents", f"{filename}.json"), 'r') as f:
                patents = json.load(f)
                patent_counts[pollutant] = len(patents)
        except:
            print(f"Error loading patents for pollutant: {pollutant}")
            patent_counts[pollutant] = 0

    # Sort pollutants by patent count
    sorted_pollutants = sorted(patent_counts.items(), key=lambda x: x[1], reverse=True)

    # Print the top 10 and bottom 10 pollutants by patent count
    print("Top 10 pollutants by patent count:")
    for pollutant, count in sorted_pollutants[:10]:
        print(f"  {pollutant}: {count} patents")

    print("\nBottom 10 pollutants by patent count (excluding zero counts):")
    bottom_pollutants = [p for p in sorted_pollutants if p[1] > 0][-10:]
    for pollutant, count in bottom_pollutants:
        print(f"  {pollutant}: {count} patents")

    # Select a mix of common and uncommon pollutants
    top_pollutants = [p[0] for p in sorted_pollutants[:2]]  # Take 2 most common
    mid_pollutants = [p[0] for p in sorted_pollutants[len(sorted_pollutants)//2:len(sorted_pollutants)//2+1]]  # Take 1 from middle
    bottom_pollutants = [p[0] for p in reversed(sorted_pollutants) if p[1] > 0][:1]  # Take 1 from bottom (with patents)

    selected_pollutants = top_pollutants + mid_pollutants + bottom_pollutants
    print(f"\nSelected pollutants for visualization: {selected_pollutants}")

    # Collect all patents across all pollutants to create a common background
    all_patents = {}
    for pollutant in pollutants:
        try:
            filename = pollutant_to_filename[pollutant]
            with open(os.path.join(data_dir, "patents", f"{filename}.json"), 'r') as f:
                patents = json.load(f)
                for patent in patents:
                    patent_id = patent['id']
                    if patent_id not in all_patents:
                        all_patents[patent_id] = {
                            'id': patent_id,
                            'x': patent['x'],
                            'y': patent['y'],
                            'title': patent['title']
                        }
        except:
            continue

    # Convert to dataframe for easier plotting
    background_df = pd.DataFrame(list(all_patents.values()))

    # Create individual plots for each selected pollutant
    for pollutant in selected_pollutants:
        try:
            filename = pollutant_to_filename[pollutant]
            with open(os.path.join(data_dir, "patents", f"{filename}.json"), 'r') as f:
                patents = json.load(f)

            # Create a dataframe for this pollutant's patents
            pollutant_df = pd.DataFrame(patents)

            # Create visualization
            plt.figure(figsize=(12, 10))

            # First plot all patents as a gray background
            plt.scatter(
                background_df['x'],
                background_df['y'],
                alpha=0.05,
                s=10,
                c='gray',
                label='Other Patents'
            )

            # Then plot this pollutant's patents colored by relevance
            scatter = plt.scatter(
                pollutant_df['x'],
                pollutant_df['y'],
                c=pollutant_df['score'],
                cmap='viridis',
                alpha=0.8,
                s=30,
                label=f'{pollutant} Patents'
            )

            # Add colorbar
            cbar = plt.colorbar(scatter)
            cbar.set_label('Relevance Score', fontsize=12)

            # Add title and labels
            plt.title(f'UMAP Projection of Patents - {pollutant}', fontsize=16)
            plt.xlabel('UMAP Dimension 1', fontsize=12)
            plt.ylabel('UMAP Dimension 2', fontsize=12)

            # Add a legend with patent count
            plt.legend([
                Line2D([0], [0], marker='o', color='w', markerfacecolor='gray', alpha=0.3, markersize=10),
                Line2D([0], [0], marker='o', color='w', markerfacecolor='green', alpha=0.8, markersize=10)
            ], [
                f'Other Patents ({len(background_df) - len(pollutant_df)})',
                f'{pollutant} Patents ({len(pollutant_df)})'
            ], loc='upper right')

            plt.grid(alpha=0.3)
            plt.tight_layout()

            # Save the figure
            safe_name = pollutant.replace('/', '_').replace('\\', '_')[:50]
            plt.savefig(os.path.join(output_dir, f"umap_{safe_name}.png"), dpi=300)
            plt.close()

        except Exception as e:
            print(f"Error creating visualization for {pollutant}: {e}")

    # Create a combined plot with all selected pollutants
    plt.figure(figsize=(14, 12))

    # Set different colors for each pollutant
    colors = ['red', 'blue', 'green', 'purple']

    # First plot all patents as a gray background
    plt.scatter(
        background_df['x'],
        background_df['y'],
        alpha=0.05,
        s=10,
        c='gray'
    )

    # Create a legend handles list
    legend_handles = [
        Line2D([0], [0], marker='o', color='w', markerfacecolor='gray', alpha=0.3, markersize=10,
               label=f'Other Patents ({len(background_df) - sum([patent_counts[p] for p in selected_pollutants])})')
    ]

    # Plot each pollutant's patents with a different color
    for i, pollutant in enumerate(selected_pollutants):
        try:
            filename = pollutant_to_filename[pollutant]
            with open(os.path.join(data_dir, "patents", f"{filename}.json"), 'r') as f:
                patents = json.load(f)

            pollutant_df = pd.DataFrame(patents)

            # Use the corresponding color
            color = colors[i % len(colors)]

            # Plot this pollutant's patents
            plt.scatter(
                pollutant_df['x'],
                pollutant_df['y'],
                c=color,
                alpha=0.6,
                s=30
            )

            # Add to legend
            legend_handles.append(
                Line2D([0], [0], marker='o', color='w', markerfacecolor=color, alpha=0.6, markersize=10,
                       label=f'{pollutant} ({len(pollutant_df)} patents)')
            )

        except Exception as e:
            print(f"Error adding {pollutant} to combined plot: {e}")

    # Add title and labels
    plt.title('UMAP Projection of Patents by Pollutant', fontsize=16)
    plt.xlabel('UMAP Dimension 1', fontsize=12)
    plt.ylabel('UMAP Dimension 2', fontsize=12)

    # Add the legend
    plt.legend(handles=legend_handles, loc='upper right')

    plt.grid(alpha=0.3)
    plt.tight_layout()

    # Save the combined figure
    plt.savefig(os.path.join(output_dir, "umap_combined_pollutants.png"), dpi=300)
    plt.close()

    # Create a heatmap of patent counts per pollutant
    # This visualization helps understand the distribution of patents across pollutants
    top_30_pollutants = [p[0] for p in sorted_pollutants[:30]]
    counts = [patent_counts[p] for p in top_30_pollutants]

    plt.figure(figsize=(12, 8))
    bars = plt.barh(range(len(top_30_pollutants)), counts, color='steelblue')

    # Add count labels to the bars
    for bar, count in zip(bars, counts):
        plt.text(
            bar.get_width() + 1,
            bar.get_y() + bar.get_height()/2,
            str(count),
            va='center'
        )

    plt.yticks(range(len(top_30_pollutants)), [p[:30] + '...' if len(p) > 30 else p for p in top_30_pollutants])
    plt.xlabel('Number of Patents')
    plt.title('Top 30 Pollutants by Patent Count')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "pollutant_patent_counts.png"), dpi=300)
    plt.close()

    print(f"Visualizations saved to {output_dir}")
    return output_dir

if __name__ == "__main__":
    output_dir = visualize_pollutant_umap()
    print(f"Visualization complete! Check {output_dir} for results.")

import os
import zipfile
import json
import shutil
import datetime
import pandas as pd
from tqdm import tqdm

def filter_and_package_dashboard_data(min_score=0.5, output_zip="dashboard_data_package.zip"):
    """
    Filter patents by minimum relevance score, then create a zip archive with only the filtered data.

    Args:
        min_score: Minimum relevance score threshold (patents below this will be excluded)
        output_zip: Filename for the output zip archive
    """
    print(f"Filtering patents with minimum score of {min_score} and packaging dashboard data...")

    # Define source directories
    processed_dir = "./processed_data"
    dashboard_dir = "./dashboard_data"

    # Create a temporary directory for organizing files
    temp_dir = "./temp_dashboard_package"
    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)

    # Create subdirectories in the temp folder
    os.makedirs(os.path.join(temp_dir, "bref"), exist_ok=True)
    os.makedirs(os.path.join(temp_dir, "dashboard"), exist_ok=True)
    os.makedirs(os.path.join(temp_dir, "dashboard", "patents"), exist_ok=True)

    # Load and filter the dashboard data
    dashboard_file = os.path.join(dashboard_dir, "dashboard_data.json")
    if not os.path.exists(dashboard_file):
        print(f"Error: Main dashboard data file not found at {dashboard_file}")
        return None

    print("Loading dashboard data...")
    with open(dashboard_file, 'r') as f:
        dashboard_data = json.load(f)

    # Load the pollutant-to-filename mapping
    mapping_file = os.path.join(dashboard_dir, "pollutant_filenames.json")
    pollutant_to_filename = {}
    if os.path.exists(mapping_file):
        with open(mapping_file, 'r') as f:
            pollutant_to_filename = json.load(f)

    # Initialize counters for filtering statistics
    total_pairs_before = 0
    total_pairs_after = 0
    pollutants_with_patents_before = 0
    pollutants_with_patents_after = 0

    # Set to track unique patent IDs before and after filtering
    all_patent_ids_before = set()
    all_patent_ids_after = set()

    # Filter patents in the dashboard data
    print("Filtering patents by relevance score...")
    filtered_patents = {}

    if 'patents' in dashboard_data:
        for pollutant, patents in tqdm(dashboard_data['patents'].items(), desc="Filtering pollutants"):
            if patents:  # Only count pollutants with patents
                pollutants_with_patents_before += 1
                total_pairs_before += len(patents)

                # Add all patent IDs to the before set
                for patent in patents:
                    all_patent_ids_before.add(patent['id'])

                # Filter patents with score >= min_score
                filtered = [patent for patent in patents if patent.get('score', 0) >= min_score]

                if filtered:  # Only count pollutants that still have patents after filtering
                    pollutants_with_patents_after += 1
                    total_pairs_after += len(filtered)
                    filtered_patents[pollutant] = filtered

                    # Add filtered patent IDs to the after set
                    for patent in filtered:
                        all_patent_ids_after.add(patent['id'])

                    # Save the filtered patents to a separate file
                    if pollutant in pollutant_to_filename:
                        filename = pollutant_to_filename[pollutant]
                    else:
                        # Clean filename for pollutant if mapping not available
                        filename = ''.join(c if c.isalnum() else '_' for c in pollutant).lower()
                        filename = filename.replace('__', '_').strip('_')

                    # Save individual patent file
                    patent_path = os.path.join(temp_dir, "dashboard", "patents", f"{filename}.json")
                    with open(patent_path, 'w') as f:
                        json.dump(filtered, f, indent=2)

        # Update the dashboard data with filtered patents
        dashboard_data['patents'] = filtered_patents

    # Filter the patents' list in 'pollutants'
    if 'pollutants' in dashboard_data:
        # Keep only pollutants that have patents after filtering
        dashboard_data['pollutants'] = [p for p in dashboard_data['pollutants'] if p in filtered_patents]

    # Filter the patent coordinates to keep only the patents we're retaining
    print("Filtering patent coordinates...")
    coords_df = None
    coords_csv_path = os.path.join(dashboard_dir, "patent_coordinates.csv")

    if os.path.exists(coords_csv_path):
        coords_df = pd.read_csv(coords_csv_path)
        print(f"Original coordinates: {len(coords_df)} patents")

        # Filter coordinates to keep only patents we're retaining
        coords_df = coords_df[coords_df['APPLN_ID'].isin(all_patent_ids_after)]
        print(f"Filtered coordinates: {len(coords_df)} patents")

        # Save filtered coordinates
        coords_df.to_csv(os.path.join(temp_dir, "dashboard", "patent_coordinates.csv"), index=False)

        # Save as JSON too
        coords_dict = coords_df.to_dict(orient='records')
        with open(os.path.join(temp_dir, "dashboard", "patent_coordinates.json"), 'w') as f:
            json.dump(coords_dict, f, indent=2)

    # Update metadata if available
    metadata = {}
    metadata_path = os.path.join(dashboard_dir, "metadata.json")
    if os.path.exists(metadata_path):
        try:
            with open(metadata_path, 'r') as f:
                metadata = json.load(f)

            # Update metadata
            metadata["filtered_min_score"] = min_score
            metadata["unique_patents_before"] = len(all_patent_ids_before)
            metadata["unique_patents_after"] = len(all_patent_ids_after)
            metadata["total_pairs_before"] = total_pairs_before
            metadata["total_pairs_after"] = total_pairs_after
            metadata["pollutants_with_patents_before"] = pollutants_with_patents_before
            metadata["pollutants_with_patents_after"] = pollutants_with_patents_after
            metadata["filter_date"] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        except Exception as e:
            print(f"Error updating metadata: {e}")
    else:
        # Create new metadata if not available
        metadata = {
            "filtered_min_score": min_score,
            "unique_patents_before": len(all_patent_ids_before),
            "unique_patents_after": len(all_patent_ids_after),
            "total_pairs_before": total_pairs_before,
            "total_pairs_after": total_pairs_after,
            "pollutants_with_patents_before": pollutants_with_patents_before,
            "pollutants_with_patents_after": pollutants_with_patents_after,
            "filter_date": datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }

    # Save updated dashboard data
    dashboard_path = os.path.join(temp_dir, "dashboard", "dashboard_data.json")
    with open(dashboard_path, 'w') as f:
        json.dump(dashboard_data, f, indent=2)

    # Save metadata
    metadata_path = os.path.join(temp_dir, "dashboard", "metadata.json")
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=2)

    # Copy other necessary files
    print("Copying additional files...")

    # Copy BREF hierarchy
    bref_hierarchy_path = os.path.join(processed_dir, "bref_hierarchy.json")
    if os.path.exists(bref_hierarchy_path):
        shutil.copy2(bref_hierarchy_path, os.path.join(temp_dir, "bref", "bref_hierarchy.json"))

    # Copy pollutant filenames mapping
    if os.path.exists(mapping_file):
        shutil.copy2(mapping_file, os.path.join(temp_dir, "dashboard", "pollutant_filenames.json"))

    # Copy SDGs data
    sdgs_path = os.path.join(dashboard_dir, "sdgs.json")
    if os.path.exists(sdgs_path):
        shutil.copy2(sdgs_path, os.path.join(temp_dir, "dashboard", "sdgs.json"))

    # Copy SDG impact data
    sdgimpact_path = os.path.join(dashboard_dir, "sdgImpact.json")
    if os.path.exists(sdgimpact_path):
        # Filter SDG impact to only include pollutants with patents
        if os.path.exists(sdgimpact_path):
            with open(sdgimpact_path, 'r') as f:
                sdg_impact = json.load(f)

            # Filter to include only pollutants with patents
            filtered_sdg_impact = {}
            for sdg, impacts in sdg_impact.items():
                filtered_impacts = [impact for impact in impacts if impact['pollutant'] in filtered_patents]
                if filtered_impacts:
                    filtered_sdg_impact[sdg] = filtered_impacts

            # Save filtered SDG impact
            with open(os.path.join(temp_dir, "dashboard", "sdgImpact.json"), 'w') as f:
                json.dump(filtered_sdg_impact, f, indent=2)

    # Create a README file with information about the package
    readme_path = os.path.join(temp_dir, "README.md")

    with open(readme_path, 'w') as f:
        f.write("# Patent Pollution Abatement Dashboard Data\n\n")
        f.write(f"Created: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        f.write("## Filtering Information\n\n")
        f.write(f"* Minimum Relevance Score: {min_score}\n")
        f.write(f"* Unique Patents Before Filtering: {len(all_patent_ids_before)}\n")
        f.write(f"* Unique Patents After Filtering: {len(all_patent_ids_after)}\n")
        f.write(f"* Patents Removed: {len(all_patent_ids_before) - len(all_patent_ids_after)} ({((len(all_patent_ids_before) - len(all_patent_ids_after)) / len(all_patent_ids_before) * 100):.1f}%)\n")
        f.write(f"* Total Patent-Pollutant Pairs Before: {total_pairs_before}\n")
        f.write(f"* Total Patent-Pollutant Pairs After: {total_pairs_after}\n")
        f.write(f"* Pollutants With Patents Before: {pollutants_with_patents_before}\n")
        f.write(f"* Pollutants With Patents After: {pollutants_with_patents_after}\n\n")

        if metadata:
            f.write("## Additional Metadata\n\n")
            for key, value in metadata.items():
                if key not in [
                    'filtered_min_score', 'unique_patents_before', 'unique_patents_after',
                    'total_pairs_before', 'total_pairs_after',
                    'pollutants_with_patents_before', 'pollutants_with_patents_after',
                    'filter_date'
                ]:
                    f.write(f"* {key}: {value}\n")
            f.write("\n")

        f.write("## Package Contents\n\n")
        dirs_to_describe = {
            "bref/": "BREF hierarchy data for the dashboard navigation",
            "dashboard/": "Main dashboard data files",
            "dashboard/patents/": "Patent data organized by pollutant"
        }

        for dir_path, description in dirs_to_describe.items():
            f.write(f"### {dir_path}\n")
            f.write(f"{description}\n\n")

            full_path = os.path.join(temp_dir, dir_path.rstrip('/'))
            if os.path.exists(full_path):
                files = [f for f in os.listdir(full_path) if os.path.isfile(os.path.join(full_path, f))]
                if files:
                    for filename in sorted(files):
                        f.write(f"* {filename}\n")
                else:
                    f.write("* (No files found in this directory)\n")
            else:
                f.write("* (Directory not found)\n")
            f.write("\n")

    # Create the zip archive
    print(f"Creating zip archive: {output_zip}...")
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Add files with a progress bar
        files_to_zip = []
        for root, _, files in os.walk(temp_dir):
            for file in files:
                files_to_zip.append((os.path.join(root, file), os.path.relpath(os.path.join(root, file), temp_dir)))

        for src_path, arcname in tqdm(files_to_zip, desc="Adding files to ZIP"):
            zipf.write(src_path, arcname)

    # Clean up temporary directory
    shutil.rmtree(temp_dir)

    # Report results
    total_size = os.path.getsize(output_zip) / (1024 * 1024)  # Size in MB
    print(f"\nArchive created successfully: {output_zip}")
    print(f"Total size: {total_size:.2f} MB")
    print(f"\nBEFORE FILTERING:")
    print(f"- Unique patents: {len(all_patent_ids_before)}")
    print(f"- Total patent-pollutant pairs: {total_pairs_before}")
    print(f"- Pollutants with patents: {pollutants_with_patents_before}")
    print(f"\nAFTER FILTERING (min score: {min_score}):")
    print(f"- Unique patents: {len(all_patent_ids_after)} ({len(all_patent_ids_after)/len(all_patent_ids_before)*100:.1f}% kept)")
    print(f"- Total patent-pollutant pairs: {total_pairs_after} ({total_pairs_after/total_pairs_before*100:.1f}% kept)")
    print(f"- Pollutants with patents: {pollutants_with_patents_after} ({pollutants_with_patents_after/pollutants_with_patents_before*100:.1f}% kept)")

    return output_zip

if __name__ == "__main__":
    # Filter patents with minimum score 0.5 and create the archive
    filter_and_package_dashboard_data(min_score=0.5)